//go:build !ignore_autogenerated

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

func (in *TargetRef) DeepCopyInto(out *TargetRef) { *out = *in }
func (in *TargetRef) DeepCopy() *TargetRef {
	if in == nil { return nil }
	out := new(TargetRef)
	in.DeepCopyInto(out)
	return out
}

func (in *OwnerRef) DeepCopyInto(out *OwnerRef) {
	*out = *in
	if in.Primary != nil {
		out.Primary = new(TargetRef)
		in.Primary.DeepCopyInto(out.Primary)
	}
	if in.Secondary != nil {
		out.Secondary = new(TargetRef)
		in.Secondary.DeepCopyInto(out.Secondary)
	}
}
func (in *OwnerRef) DeepCopy() *OwnerRef {
	if in == nil { return nil }
	out := new(OwnerRef)
	in.DeepCopyInto(out)
	return out
}

func (in *MatchRule) DeepCopyInto(out *MatchRule) {
	*out = *in
	if in.Labels != nil {
		out.Labels = make(map[string]string, len(in.Labels))
		for k, v := range in.Labels { out.Labels[k] = v }
	}
}
func (in *MatchRule) DeepCopy() *MatchRule {
	if in == nil { return nil }
	out := new(MatchRule)
	in.DeepCopyInto(out)
	return out
}

func (in *OwnershipRule) DeepCopyInto(out *OwnershipRule) {
	*out = *in
	in.Match.DeepCopyInto(&out.Match)
	in.Owner.DeepCopyInto(&out.Owner)
}
func (in *OwnershipRule) DeepCopy() *OwnershipRule {
	if in == nil { return nil }
	out := new(OwnershipRule)
	in.DeepCopyInto(out)
	return out
}

func (in *OwnershipPolicySpec) DeepCopyInto(out *OwnershipPolicySpec) {
	*out = *in
	in.DefaultOwner.DeepCopyInto(&out.DefaultOwner)
	if in.Rules != nil {
		out.Rules = make([]OwnershipRule, len(in.Rules))
		for i := range in.Rules { in.Rules[i].DeepCopyInto(&out.Rules[i]) }
	}
}
func (in *OwnershipPolicySpec) DeepCopy() *OwnershipPolicySpec {
	if in == nil { return nil }
	out := new(OwnershipPolicySpec)
	in.DeepCopyInto(out)
	return out
}

func (in *OwnershipPolicyStatus) DeepCopyInto(out *OwnershipPolicyStatus) { *out = *in }
func (in *OwnershipPolicyStatus) DeepCopy() *OwnershipPolicyStatus {
	if in == nil { return nil }
	out := new(OwnershipPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *AlertMatchRule) DeepCopyInto(out *AlertMatchRule) {
	*out = *in
	if in.Labels != nil {
		out.Labels = make(map[string]string, len(in.Labels))
		for k, v := range in.Labels { out.Labels[k] = v }
	}
}
func (in *AlertMatchRule) DeepCopy() *AlertMatchRule {
	if in == nil { return nil }
	out := new(AlertMatchRule)
	in.DeepCopyInto(out)
	return out
}

func (in *AlertOwnershipRule) DeepCopyInto(out *AlertOwnershipRule) {
	*out = *in
	in.Match.DeepCopyInto(&out.Match)
	in.Owner.DeepCopyInto(&out.Owner)
}
func (in *AlertOwnershipRule) DeepCopy() *AlertOwnershipRule {
	if in == nil { return nil }
	out := new(AlertOwnershipRule)
	in.DeepCopyInto(out)
	return out
}

func (in *AlertOwnershipPolicySpec) DeepCopyInto(out *AlertOwnershipPolicySpec) {
	*out = *in
	in.DefaultOwner.DeepCopyInto(&out.DefaultOwner)
	if in.Rules != nil {
		out.Rules = make([]AlertOwnershipRule, len(in.Rules))
		for i := range in.Rules { in.Rules[i].DeepCopyInto(&out.Rules[i]) }
	}
}
func (in *AlertOwnershipPolicySpec) DeepCopy() *AlertOwnershipPolicySpec {
	if in == nil { return nil }
	out := new(AlertOwnershipPolicySpec)
	in.DeepCopyInto(out)
	return out
}

func (in *AlertOwnershipPolicyStatus) DeepCopyInto(out *AlertOwnershipPolicyStatus) { *out = *in }
func (in *AlertOwnershipPolicyStatus) DeepCopy() *AlertOwnershipPolicyStatus {
	if in == nil { return nil }
	out := new(AlertOwnershipPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *OwnershipPolicy) DeepCopyInto(out *OwnershipPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}
func (in *OwnershipPolicy) DeepCopy() *OwnershipPolicy {
	if in == nil { return nil }
	out := new(OwnershipPolicy)
	in.DeepCopyInto(out)
	return out
}
func (in *OwnershipPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *OwnershipPolicyList) DeepCopyInto(out *OwnershipPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]OwnershipPolicy, len(in.Items))
		for i := range in.Items { in.Items[i].DeepCopyInto(&out.Items[i]) }
	}
}
func (in *OwnershipPolicyList) DeepCopy() *OwnershipPolicyList {
	if in == nil { return nil }
	out := new(OwnershipPolicyList)
	in.DeepCopyInto(out)
	return out
}
func (in *OwnershipPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *AlertOwnershipPolicy) DeepCopyInto(out *AlertOwnershipPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}
func (in *AlertOwnershipPolicy) DeepCopy() *AlertOwnershipPolicy {
	if in == nil { return nil }
	out := new(AlertOwnershipPolicy)
	in.DeepCopyInto(out)
	return out
}
func (in *AlertOwnershipPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *AlertOwnershipPolicyList) DeepCopyInto(out *AlertOwnershipPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]AlertOwnershipPolicy, len(in.Items))
		for i := range in.Items { in.Items[i].DeepCopyInto(&out.Items[i]) }
	}
}
func (in *AlertOwnershipPolicyList) DeepCopy() *AlertOwnershipPolicyList {
	if in == nil { return nil }
	out := new(AlertOwnershipPolicyList)
	in.DeepCopyInto(out)
	return out
}
func (in *AlertOwnershipPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}
