from __future__ import annotations

from typing import Any

ALERT_PRESETS: list[dict[str, Any]] = [
    {
        "id": "host-cpu-high",
        "label": "Host CPU above 90%",
        "description": "Trigger when host CPU remains above 90%.",
        "severity": "critical",
        "target_type": "host",
        "condition": {"metric": "cpu_percent", "operator": ">", "value": 90, "duration_minutes": 5},
        "scope": {},
        "cooldown_seconds": 300,
    },
    {
        "id": "host-memory-high",
        "label": "Host memory above 85%",
        "description": "Trigger when host memory stays above 85%.",
        "severity": "warning",
        "target_type": "host",
        "condition": {"metric": "memory_percent", "operator": ">", "value": 85, "duration_minutes": 5},
        "scope": {},
        "cooldown_seconds": 300,
    },
    {
        "id": "host-disk-high",
        "label": "Host disk above 90%",
        "description": "Trigger when host disk usage exceeds 90%.",
        "severity": "critical",
        "target_type": "host",
        "condition": {"metric": "disk_percent", "operator": ">", "value": 90, "duration_minutes": 10},
        "scope": {},
        "cooldown_seconds": 600,
    },
    {
        "id": "service-latency-high",
        "label": "Service latency above 250ms",
        "description": "Trigger when a monitored service gets slow.",
        "severity": "warning",
        "target_type": "service",
        "condition": {"metric": "latency_ms", "operator": ">", "value": 250, "duration_minutes": 3},
        "scope": {},
        "cooldown_seconds": 300,
    },
    {
        "id": "service-uptime-low",
        "label": "Service uptime below 99.5%",
        "description": "Trigger when service uptime drops below SLO.",
        "severity": "critical",
        "target_type": "service",
        "condition": {"metric": "uptime_percent", "operator": "<", "value": 99.5},
        "scope": {},
        "cooldown_seconds": 900,
    },
    {
        "id": "postgres-primary-health",
        "label": "PostgreSQL latency above 200ms",
        "description": "Trigger when PostgreSQL services are slow.",
        "severity": "warning",
        "target_type": "service",
        "condition": {"metric": "latency_ms", "operator": ">", "value": 200, "duration_minutes": 3},
        "scope": {"plugin_id": "postgres", "service_type": "postgresql"},
        "cooldown_seconds": 300,
    },
    {
        "id": "mysql-core-health",
        "label": "MySQL latency above 200ms",
        "description": "Trigger when MySQL services are slow.",
        "severity": "warning",
        "target_type": "service",
        "condition": {"metric": "latency_ms", "operator": ">", "value": 200, "duration_minutes": 3},
        "scope": {"plugin_id": "mysql", "service_type": "mysql"},
        "cooldown_seconds": 300,
    },
    {
        "id": "redis-cache-health",
        "label": "Redis latency above 75ms",
        "description": "Trigger when Redis cache services slow down.",
        "severity": "warning",
        "target_type": "service",
        "condition": {"metric": "latency_ms", "operator": ">", "value": 75, "duration_minutes": 2},
        "scope": {"plugin_id": "redis", "service_type": "redis"},
        "cooldown_seconds": 180,
    },
    {
        "id": "redis-throughput-health",
        "label": "Redis uptime below 99.5%",
        "description": "Trigger when Redis-backed queue/session infrastructure loses availability.",
        "severity": "critical",
        "target_type": "service",
        "condition": {"metric": "uptime_percent", "operator": "<", "value": 99.5},
        "scope": {"plugin_id": "redis", "service_type": "redis"},
        "cooldown_seconds": 300,
    },
    {
        "id": "rabbitmq-core-health",
        "label": "RabbitMQ uptime below 99%",
        "description": "Trigger when RabbitMQ availability drops.",
        "severity": "critical",
        "target_type": "service",
        "condition": {"metric": "uptime_percent", "operator": "<", "value": 99},
        "scope": {"plugin_id": "rabbitmq", "service_type": "rabbitmq"},
        "cooldown_seconds": 600,
    },
    {
        "id": "docker-runtime-health",
        "label": "Docker uptime below 99%",
        "description": "Trigger when the Docker runtime looks unhealthy.",
        "severity": "critical",
        "target_type": "service",
        "condition": {"metric": "uptime_percent", "operator": "<", "value": 99},
        "scope": {"plugin_id": "docker-local", "service_type": "docker-container"},
        "cooldown_seconds": 600,
    },
    {
        "id": "docker-swarm-health",
        "label": "Docker Swarm uptime below 99%",
        "description": "Trigger when a Docker Swarm node loses availability.",
        "severity": "critical",
        "target_type": "service",
        "condition": {"metric": "uptime_percent", "operator": "<", "value": 99},
        "scope": {"plugin_id": "docker-local", "service_type": "docker-container"},
        "cooldown_seconds": 600,
    },
    {
        "id": "prometheus-core-health",
        "label": "Prometheus uptime below 99.5%",
        "description": "Trigger when Prometheus availability drops.",
        "severity": "critical",
        "target_type": "service",
        "condition": {"metric": "uptime_percent", "operator": "<", "value": 99.5},
        "scope": {"plugin_id": "prometheus", "service_type": "prometheus"},
        "cooldown_seconds": 600,
    },
    {
        "id": "prometheus-target-health",
        "label": "Prometheus latency above 400ms",
        "description": "Trigger when Prometheus scrape/query responsiveness degrades.",
        "severity": "warning",
        "target_type": "service",
        "condition": {"metric": "latency_ms", "operator": ">", "value": 400, "duration_minutes": 3},
        "scope": {"plugin_id": "prometheus", "service_type": "prometheus"},
        "cooldown_seconds": 300,
    },
    {
        "id": "k3s-cluster-health",
        "label": "Kubernetes uptime below 99%",
        "description": "Trigger when K3s control-plane availability drops.",
        "severity": "critical",
        "target_type": "service",
        "condition": {"metric": "uptime_percent", "operator": "<", "value": 99},
        "scope": {"plugin_id": "kubernetes", "service_type": "kubernetes"},
        "cooldown_seconds": 600,
    },
    {
        "id": "kubernetes-edge-health",
        "label": "Kubernetes latency above 400ms",
        "description": "Trigger when a small edge Kubernetes cluster becomes slow to respond.",
        "severity": "warning",
        "target_type": "service",
        "condition": {"metric": "latency_ms", "operator": ">", "value": 400, "duration_minutes": 3},
        "scope": {"plugin_id": "kubernetes", "service_type": "kubernetes"},
        "cooldown_seconds": 300,
    },
    {
        "id": "nginx-edge-health",
        "label": "Nginx uptime below 99.5%",
        "description": "Trigger when an Nginx edge surface loses availability.",
        "severity": "critical",
        "target_type": "service",
        "condition": {"metric": "uptime_percent", "operator": "<", "value": 99.5},
        "scope": {"plugin_id": "nginx"},
        "cooldown_seconds": 300,
    },
    {
        "id": "mongodb-core-health",
        "label": "MongoDB latency above 250ms",
        "description": "Trigger when MongoDB services are slow.",
        "severity": "warning",
        "target_type": "service",
        "condition": {"metric": "latency_ms", "operator": ">", "value": 250, "duration_minutes": 3},
        "scope": {"plugin_id": "mongodb", "service_type": "mongodb"},
        "cooldown_seconds": 300,
    },
    {
        "id": "elasticsearch-health",
        "label": "Elasticsearch latency above 300ms",
        "description": "Trigger when Elasticsearch becomes slow to respond.",
        "severity": "warning",
        "target_type": "service",
        "condition": {"metric": "latency_ms", "operator": ">", "value": 300, "duration_minutes": 3},
        "scope": {"plugin_id": "elasticsearch", "service_type": "elasticsearch"},
        "cooldown_seconds": 300,
    },
    {
        "id": "kafka-core-health",
        "label": "Kafka uptime below 99%",
        "description": "Trigger when Kafka broker availability drops.",
        "severity": "critical",
        "target_type": "service",
        "condition": {"metric": "uptime_percent", "operator": "<", "value": 99},
        "scope": {"plugin_id": "kafka", "service_type": "kafka"},
        "cooldown_seconds": 600,
    },
    {
        "id": "nats-core-health",
        "label": "NATS uptime below 99.5%",
        "description": "Trigger when NATS messaging availability drops.",
        "severity": "critical",
        "target_type": "service",
        "condition": {"metric": "uptime_percent", "operator": "<", "value": 99.5},
        "scope": {"plugin_id": "nats", "service_type": "nats"},
        "cooldown_seconds": 300,
    },
]

ALERT_PRESETS_BY_ID: dict[str, dict[str, Any]] = {preset["id"]: preset for preset in ALERT_PRESETS}


def get_alert_preset(preset_id: str) -> dict[str, Any] | None:
    preset = ALERT_PRESETS_BY_ID.get(preset_id)
    if not preset:
        return None
    return {**preset, "condition": {**preset["condition"]}, "scope": {**preset.get("scope", {})}}
