import fs from "node:fs";
import path from "node:path";

const pluginRepo = process.env.VORDR_PLUGINS_REPO || path.resolve(process.cwd(), "..", "..", "vordr-plugins");
const manifestsDir = path.join(pluginRepo, "manifests");
const outFile = path.resolve(process.cwd(), "src", "generated", "plugins.generated.ts");

if (!fs.existsSync(manifestsDir)) {
  throw new Error(`Plugin manifests directory not found: ${manifestsDir}`);
}

const manifests = fs.readdirSync(manifestsDir)
  .filter((name) => name.endsWith('.json'))
  .sort()
  .map((name) => {
    const fullPath = path.join(manifestsDir, name);
    return JSON.parse(fs.readFileSync(fullPath, 'utf8'));
  });

const normalized = manifests.map((plugin) => ({
  downloads: 0,
  rating: 5,
  repoUrl: 'https://github.com/hijak/vordr-plugins',
  verified: true,
  ...plugin,
}));

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(
  outFile,
  `/* auto-generated by scripts/sync-plugins.mjs */\nexport interface GeneratedPlugin {\n  id: string;\n  name: string;\n  description: string;\n  author: string;\n  category: string;\n  downloads: number;\n  rating: number;\n  version: string;\n  iconKey: string;\n  verified: boolean;\n  tags: string[];\n  repoUrl: string;\n  sourcePath: string;\n  status: "official" | "experimental";\n  maturity: "alpha" | "beta" | "stable";\n  integration: "agent" | "backend" | "ui" | "hybrid";\n  summary: string[];\n  config: Record<string, string | boolean | number>;\n}\n\nexport const generatedPlugins: GeneratedPlugin[] = ${JSON.stringify(normalized, null, 2)} as const;\n`,
  'utf8'
);

console.log(`Generated ${outFile} from ${manifests.length} plugin manifest(s)`);
