import fs from "node:fs";
import path from "node:path";

const pluginRepo = process.env.VORDR_PLUGINS_REPO || path.resolve(process.cwd(), "..", "..", "vordr-plugins");
const manifestsDir = path.join(pluginRepo, "manifests");
const outFile = path.resolve(process.cwd(), "src", "generated", "plugins.generated.ts");

if (!fs.existsSync(manifestsDir)) {
  if (fs.existsSync(outFile)) {
    console.log(`Plugin manifests directory not found: ${manifestsDir}; keeping existing generated catalogue at ${outFile}`);
    process.exit(0);
  }
  throw new Error(`Plugin manifests directory not found: ${manifestsDir}`);
}

const manifests = fs.readdirSync(manifestsDir)
  .filter((name) => name.endsWith('.json'))
  .sort()
  .map((name) => {
    const fullPath = path.join(manifestsDir, name);
    return JSON.parse(fs.readFileSync(fullPath, 'utf8'));
  });

function sanitize(value) {
  if (typeof value === 'string') {
    return value
      .replaceAll('Argus Core', 'Vordr Core')
      .replaceAll('mysql://argus:arguspass', 'mysql://vordr:changeme')
      .replaceAll('postgresql://argus:arguspass', 'postgresql://vordr:changeme')
      .replaceAll('"arguspass"', '"changeme"')
      .replaceAll('"argus"', '"vordr"');
  }
  if (Array.isArray(value)) return value.map(sanitize);
  if (value && typeof value === 'object') {
    return Object.fromEntries(Object.entries(value).map(([k, v]) => [k, sanitize(v)]));
  }
  return value;
}

const normalized = manifests.map((plugin) => sanitize({
  downloads: 0,
  rating: 5,
  repoUrl: 'https://github.com/hijak/vordr-plugins',
  verified: true,
  ...plugin,
}));

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(
  outFile,
  `/* auto-generated by scripts/sync-plugins.mjs */
export interface GeneratedPluginProfile {
  id: string;
  name: string;
  description: string;
  whenToSuggest?: string[];
  dashboardPresetIds?: string[];
  alertPresetIds?: string[];
  serviceGroups?: string[];
  tags?: string[];
}

export interface GeneratedPlugin {
  id: string;
  name: string;
  description: string;
  author: string;
  category: string;
  family: string;
  kind: "technology" | "profile";
  downloads: number;
  rating: number;
  version: string;
  iconKey: string;
  verified: boolean;
  tags: string[];
  repoUrl: string;
  sourcePath: string;
  serviceType: string;
  status: "official" | "experimental";
  maturity: "alpha" | "beta" | "stable";
  integration: "agent" | "backend" | "ui" | "hybrid";
  summary: string[];
  config: Record<string, string | boolean | number>;
  discovery: {
    methods: string[];
    target?: string;
    promotedFrom?: string[];
    notes?: string[];
  };
  fingerprints?: Record<string, string[] | number[]>;
  profiles?: GeneratedPluginProfile[];
  appliesTo?: {
    pluginIds?: string[];
    serviceTypes?: string[];
    families?: string[];
  };
}

export const generatedPlugins: GeneratedPlugin[] = ${JSON.stringify(normalized, null, 2)} as const;
`,
  'utf8'
);

console.log(`Generated ${outFile} from ${manifests.length} plugin manifest(s)`);
