FROM golang:1.25 AS builder
WORKDIR /workspace
COPY go.mod .
COPY api ./api
COPY controllers ./controllers
COPY main.go .
RUN go mod tidy && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o manager main.go

FROM gcr.io/distroless/static:nonroot
WORKDIR /
COPY --from=builder /workspace/manager .
USER 65532:65532
ENTRYPOINT ["/manager"]
